### ISSUE TITLE
syaning域名过期

### ISSUE THREAD

**Issue by heyeshuang** [syaning/syaning.github.io#1]
本来保存了两篇博文准备“稍后阅读”的😂

**Comment by syaning** [comment]
之前在一个小的代理商那里注册的域名，想要转出，但是没成功。就没管它，等域名过期了再去注册。取消了CNAME，暂时可以通过 http://syaning.github.io/ 来访问了

**Comment by heyeshuang** [comment]
OK，下次再看🤣
